# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_column=b'mac', max_length=32, unique=True)),
                ('ip', models.CharField(blank=True, db_column=b'ip', max_length=64, null=True)),
                ('ssid', models.CharField(blank=True, db_column=b'ssid', max_length=100, null=True)),
                ('model', models.CharField(blank=True, db_column=b'model', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_column=b'location', max_length=1000, null=True)),
                ('location1', models.CharField(blank=True, db_column=b'location_1', max_length=100, null=True)),
                ('location2', models.CharField(blank=True, db_column=b'location_2', max_length=100, null=True)),
                ('location3', models.CharField(blank=True, db_column=b'location_3', max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now=True, db_column=b'time')),
                ('longitudes', models.CharField(blank=True, db_column=b'longitudes', max_length=100, null=True)),
                ('latitudes', models.CharField(blank=True, db_column=b'latitudes', max_length=100, null=True)),
                ('remark', models.CharField(blank=True, db_column=b'remark', max_length=1000, null=True)),
                ('wifi_password', models.CharField(blank=True, db_column=b'wifi_password', max_length=100, null=True)),
                ('login_name', models.CharField(blank=True, db_column=b'login_name', max_length=100, null=True)),
                ('login_password', models.CharField(blank=True, db_column=b'login_password', max_length=100, null=True)),
                ('login_url', models.CharField(blank=True, db_column=b'login_url', max_length=100, null=True)),
                ('status', models.SmallIntegerField(db_column=b'status', default=0)),
                ('ver', models.CharField(blank=True, db_column=b'version', max_length=100, null=True)),
                ('encrypt', models.CharField(blank=True, db_column=b'encrypt', max_length=100, null=True)),
                ('source_ssid', models.CharField(blank=True, db_column=b'source_ssid', max_length=100, null=True)),
            ],
            options={
                'db_table': 't_route',
            },
        ),
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.IntegerField(db_column=b'monitor_id')),
                ('strength', models.SmallIntegerField(blank=True, db_column=b'strength', null=True)),
                ('time', models.DateTimeField(auto_now=True, db_column=b'time')),
                ('hotspot', models.ForeignKey(db_column=b'route_id', on_delete=django.db.models.deletion.CASCADE, to='Hotspot.Hotspot')),
            ],
            options={
                'db_table': 't_hotspot',
            },
        ),
    ]
