# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_column=b'mac', max_length=32, unique=True)),
                ('name', models.CharField(db_column=b'name', max_length=100)),
                ('time', models.DateTimeField(auto_now=True, db_column=b'create_time')),
                ('x', models.CharField(blank=True, db_column=b'x', max_length=100, null=True)),
                ('y', models.CharField(blank=True, db_column=b'y', max_length=100, null=True)),
                ('count', models.IntegerField(db_column=b'count', default=0)),
                ('ver', models.CharField(blank=True, db_column=b'ver', max_length=100, null=True)),
                ('type', models.SmallIntegerField(db_column=b'type', default=0)),
                ('ip', models.CharField(blank=True, db_column=b'ip', max_length=100, null=True)),
                ('remark', models.CharField(blank=True, db_column=b'remark', max_length=100, null=True)),
            ],
            options={
                'db_table': 't_monitor',
            },
        ),
    ]
